#use_frameworks! :linkage => :static
use_modular_headers!

platform :ios, '10.0'

target 'SChainWallet_Example' do
  pod 'SChainWallet', :path => '../'

  target 'SChainWallet_Tests' do
    inherit! :search_paths
  end
end
